<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>

    <PackageId>Verdict.Logging</PackageId>
    <Description>Baryo.Dev: Logging extensions for Verdict. Automatic logging integration with Microsoft.Extensions.Logging for success and error flows.</Description>
    <PackageTags>result;logging;microsoft-extensions-logging</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Verdict\Verdict.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>
</Project>
