<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    
    <!-- Package Metadata -->
    <PackageId>Verdict</PackageId>
    <Description>Baryo.Dev: High-performance result pattern. Zero-dependency, zero-allocation (on success) Result&lt;T&gt; for fast control flow without exceptions.</Description>
    <PackageTags>result;error-handling;functional;performance;zero-allocation</PackageTags>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
